version: '3.8'
services:
  db:
    image: postgres:13
    container_name: real_estate_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:   
      POSTGRES_DB: real_estate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
